include ../Makefile.include
LIB_HEADERS=reduce.hpp
DESIGNS=reduce_min rreduce_min for_min reduce_add rreduce_add for_add \
rreduce_map reduce_map for_map reduce_reverse for_reverse rreduce_reverse \
rreduce_interleave reduce_interleave for_interleave
